name: dona_ya
description: "A donation app"
publish_to: 'none'

version: 1.0.0-alpha.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cached_network_image_web: ^1.3.1
  cached_network_image_platform_interface: ^4.1.1
  collection: ^1.19.1
  easy_debounce: ^2.0.3
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^10.10.0
  flutter_cache_manager: ^3.4.1
  from_css_color: ^2.0.0
  go_router: ^16.2.0
  google_fonts: ^6.3.1
  intl: ^0.20.2
  json_path: ^0.8.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.18
  path_provider_foundation: ^2.4.2
  path_provider_linux: ^2.2.1
  path_provider_platform_interface: ^2.1.2
  percent_indicator: ^4.2.5
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.12
  shared_preferences_linux: ^2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_foundation: ^2.5.4
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  sqflite_common: ^2.5.6
  url_launcher: ^6.3.2
  url_launcher_android: ^6.3.18
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  const_date_time: ^1.2.1
  formz: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_lint: ^0.3.1
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true